# -*- coding: utf-8 -*-
"""Time_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQAv11vCBsLCFJ_S4KB1rr5NjLl_a4zB
"""

def convert_minutes(minutes):
    hours = minutes // 60  # Integer division for hours
    remaining_minutes = minutes % 60  # Modulo for minutes
    if hours == 1:
        hour_str = "1hr"
    else:
        hour_str = f"{hours} hrs"
    if remaining_minutes == 1:
        min_str = "1 minute"
    else:
        min_str = f"{remaining_minutes} minutes"
    if hours == 0:
        return min_str
    elif remaining_minutes == 0:
        return hour_str
    else:
        return f"{hour_str} {min_str}"

print(convert_minutes(130))
print(convert_minutes(110))
print(convert_minutes(1))
print(convert_minutes(60))

def remove_duplicates(input_string):
    result = ""  # Empty string to build unique chars
    for char in input_string:  # Loop through each character
        if char not in result:  # If not already in result, add it
            result += char
    return result

# Test
print(remove_duplicates("hello"))  # Output: helo
print(remove_duplicates("aabbcc")) # Output: abc
print(remove_duplicates("abc"))    # Output: abc (no duplicates)

